-- MySQL Script generated by MySQL Workbench
-- 11/18/15 15:53:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=TRADITIONAL,ALLOW_INVALID_DATES;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS lap DEFAULT CHARACTER SET latin1 ;
USE lap ;

-- -----------------------------------------------------
-- Table lap.option_groups
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.option_groups (
  id INT(11) NOT NULL AUTO_INCREMENT,
  option_group_name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = This is our survey tool.;


-- -----------------------------------------------------
-- Table lap.option_choices
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.option_choices (
  id INT(11) NOT NULL AUTO_INCREMENT,
  option_group_id INT(11) NOT NULL,
  option_choice_name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_option_type_choices_option_type_group1 (option_group_id ASC),
  CONSTRAINT fk_option_type_choices_option_type_group1
    FOREIGN KEY (option_group_id)
    REFERENCES lap.option_groups (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = This is our survey tool.;


-- -----------------------------------------------------
-- Table lap.input_types
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.input_types (
  id INT(11) NOT NULL AUTO_INCREMENT,
  input_type_name VARCHAR(80) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX survey_name_UNIQUE (input_type_name ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = This is our survey tool.;


-- -----------------------------------------------------
-- Table lap.organizations
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.organizations (
  id INT(11) NOT NULL AUTO_INCREMENT,
  subject VARCHAR(80) NOT NULL,
  course_number INT(11) NOT NULL,
  quarter INT(11) NOT NULL,
  year INT(11) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = This is our survey tool.;


-- -----------------------------------------------------
-- Table lap.survey_headers
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.survey_headers (
  id INT(11) NOT NULL AUTO_INCREMENT,
  organization_id INT(11) NOT NULL,
  survey_name VARCHAR(80) NULL DEFAULT NULL,
  instructions VARCHAR(4096) NULL DEFAULT NULL,
  other_header_info VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX survey_name_UNIQUE (survey_name ASC),
  INDEX fk_surveys_organizations1 (organization_id ASC),
  CONSTRAINT fk_surveys_organizations1
    FOREIGN KEY (organization_id)
    REFERENCES lap.organizations (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = This is our survey tool.;


-- -----------------------------------------------------
-- Table lap.survey_sections
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.survey_sections (
  id INT(11) NOT NULL AUTO_INCREMENT,
  survey_header_id INT(11) NULL DEFAULT NULL,
  section_name VARCHAR(80) NULL DEFAULT NULL,
  section_title VARCHAR(45) NULL DEFAULT NULL,
  section_subheading VARCHAR(45) NULL DEFAULT NULL,
  section_required_yn TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE INDEX survey_name_UNIQUE (section_name ASC),
  INDEX fk_survey_sections_surveys1 (survey_header_id ASC),
  CONSTRAINT fk_survey_sections_surveys1
    FOREIGN KEY (survey_header_id)
    REFERENCES lap.survey_headers (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = This is our survey tool.;


-- -----------------------------------------------------
-- Table lap.questions
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.questions (
  id INT(11) NOT NULL AUTO_INCREMENT,
  parent_id INT(11) NULL DEFAULT NULL,
  survey_section_id INT(11) NOT NULL,
  input_type_id INT(11) NOT NULL,
  question_name VARCHAR(255) NOT NULL,
  question_subtext VARCHAR(500) NULL DEFAULT NULL,
  question_required_yn TINYINT(1) NULL DEFAULT NULL,
  answer_required_yn TINYINT(1) NULL DEFAULT 1,
  option_group_id INT(11) NULL DEFAULT NULL,
  allow_mutiple_option_answers_yn TINYINT(1) NULL DEFAULT 0,
  dependent_question_id INT(11) NULL DEFAULT NULL,
  dependent_question_option_id INT(11) NULL DEFAULT NULL,
  dependent_answer_id INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX allow_mutiple_option_answers_yn_UNIQUE (allow_mutiple_option_answers_yn ASC),
  INDEX fk_questions_question_types1 (input_type_id ASC),
  INDEX fk_questions_survey_sections1 (survey_section_id ASC),
  INDEX fk_questions_option_type_group1 (option_group_id ASC),
  CONSTRAINT fk_questions_option_type_group1
    FOREIGN KEY (option_group_id)
    REFERENCES lap.option_groups (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_questions_question_types1
    FOREIGN KEY (input_type_id)
    REFERENCES lap.input_types (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_questions_survey_sections1
    FOREIGN KEY (survey_section_id)
    REFERENCES lap.survey_sections (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = This is are our questions;


-- -----------------------------------------------------
-- Table lap.question_options
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.question_options (
  id INT(11) NOT NULL,
  question_id INT(11) NOT NULL,
  option_choice_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_question_options_questions1 (question_id ASC),
  INDEX fk_question_options_option_choices1 (option_choice_id ASC),
  CONSTRAINT fk_question_options_option_choices1
    FOREIGN KEY (option_choice_id)
    REFERENCES lap.option_choices (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_question_options_questions1
    FOREIGN KEY (question_id)
    REFERENCES lap.questions (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table lap.users
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  organization_id INT NOT NULL COMMENT To keep track of students from different classes, organizations, etc.,
  username VARCHAR(80) NOT NULL,
  password_hashed VARCHAR(255) NULL DEFAULT NULL,
  email VARCHAR(45) NOT NULL,
  admin TINYINT(1) NULL DEFAULT NULL,
  invite_dt DATETIME NULL DEFAULT NULL,
  last_login_dt DATETIME NULL DEFAULT NULL,
  inviter_user_id INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX survey_name_UNIQUE (username ASC),
  UNIQUE INDEX email_UNIQUE (email ASC),
  INDEX id_idx (organization_id ASC),
  CONSTRAINT id
    FOREIGN KEY (organization_id)
    REFERENCES lap.organizations (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = This is our survey tool.;


-- -----------------------------------------------------
-- Table lap.answers
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.answers (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  question_option_id INT(11) NOT NULL,
  answer_numeric INT(11) NULL DEFAULT NULL,
  answer_text VARCHAR(255) NULL DEFAULT NULL,
  answer_yn TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX fk_answers_surveyees1 (user_id ASC),
  INDEX fk_answers_question_options1 (question_option_id ASC),
  CONSTRAINT fk_answers_question_options1
    FOREIGN KEY (question_option_id)
    REFERENCES lap.question_options (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_answers_surveyees1
    FOREIGN KEY (user_id)
    REFERENCES lap.users (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = This is are our answers;


-- -----------------------------------------------------
-- Table lap.species_types
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.species_types (
  id INT(11) NOT NULL AUTO_INCREMENT,
  species_name VARCHAR(45) NOT NULL COMMENT species_name = trees, birds, shrubs,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table lap.species
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.species (
  id INT(11) NOT NULL AUTO_INCREMENT,
  species_type_id INT(11) NOT NULL,
  common_name VARCHAR(45) NOT NULL,
  scientific_name VARCHAR(255) NULL DEFAULT NULL,
  general_info VARCHAR(4096) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX id_idx (species_type_id ASC),
  CONSTRAINT id
    FOREIGN KEY (species_type_id)
    REFERENCES lap.species_types (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table lap.survey_comments
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.survey_comments (
  id INT(11) NOT NULL,
  survey_header_id INT(11) NOT NULL,
  user_id INT(11) NOT NULL,
  comments VARCHAR(4096) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX fk_survey_comments_users1 (user_id ASC),
  INDEX fk_survey_comments_surveys1 (survey_header_id ASC),
  CONSTRAINT fk_survey_comments_surveys1
    FOREIGN KEY (survey_header_id)
    REFERENCES lap.survey_headers (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_survey_comments_users1
    FOREIGN KEY (user_id)
    REFERENCES lap.users (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table lap.user_survey_sections
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS lap.user_survey_sections (
  id INT(11) NOT NULL,
  user_id INT(11) NOT NULL,
  survey_section_id INT(11) NOT NULL,
  completed_on DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX fk_user_survey_sections_survey_sections1 (survey_section_id ASC),
  INDEX fk_user_survey_sections_users1 (user_id ASC),
  CONSTRAINT fk_user_survey_sections_survey_sections1
    FOREIGN KEY (survey_section_id)
    REFERENCES lap.survey_sections (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_user_survey_sections_users1
    FOREIGN KEY (user_id)
    REFERENCES lap.users (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
